name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload app to EC2 via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "app.py,requirements.txt,Dockerfile"
          target: "/home/ubuntu/flask-app"

      - name: Build & Run on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /home/ubuntu/flask-app
            docker stop flask-aws || true
            docker rm flask-aws || true
            docker build -t flask-aws:latest .
            docker run -d --name flask-aws -p 80:5000 flask-aws:latest
            docker image prune -f
